import type { Service } from "./types";

const S = "/expertises/service-onderhoud";
const DG = `${S}/dak-en-gevelonderhoud`;
const B = `${S}/balkononderhoud`;
const BKT = `${S}/badkamer-keuken-toilet-onderhoud-bkt`;
const I = `${S}/interieur`;
const K = `${S}/kozijnen`;
const G = "/expertises/renovatie-verbouw/verduurzaming/gevelrenovatie";

export const onderhoud: Service[] = [
  {
    path: S,
    name: "Service & onderhoud",
    short: "Vast onderhoud voor dak, gevel, balkon, natte ruimtes, interieur en kozijnen.",
    h1: "Service en onderhoud voor woning en vastgoed",
    title: "Service en onderhoud woning en vastgoed",
    description:
      "Onderhoud aan dak, gevel, balkon, badkamer, interieur en kozijnen in Zeeland, West-Brabant en Amsterdam. Voor particulier en VvE. Vraag een offerte aan.",
    icon: "wrench",
    intro: [
      "Onderhoud is minder spannend dan een verbouwing, maar het levert meer op. Een kitvoeg op tijd vervangen voorkomt een lekkage. Een dakgoot die vrij blijft, voorkomt een natte gevel. Kleine gebreken die je laat zitten, worden grote rekeningen.",
      "Wij doen onderhoud aan de buitenkant en de binnenkant van woningen en complexen. Van dakpannen en voegwerk tot kitwerk in de badkamer, houtrot in kozijnen en schilderwerk binnen. Je kunt ons inschakelen voor een losse klus of voor periodiek onderhoud.",
      "Voor VvE's, woningcorporaties en vastgoedbeheerders werken we met meerjarenplanningen en mutatieonderhoud. Dan heb je één vaste partij die de gebouwen kent en snel kan schakelen.",
    ],
    signals: [
      "Je ziet kleine gebreken die erger worden",
      "Je wilt onderhoud vooruit plannen in plaats van achteraf repareren",
      "Je beheert meerdere woningen of een complex",
    ],
    duration: "Losse onderhoudsklussen zijn vaak binnen een dag tot een week klaar. Periodiek onderhoud plannen we per seizoen.",
    costFactors: [
      "Soort en omvang van het onderhoud",
      "Bereikbaarheid (steiger of hoogwerker)",
      "Losse klus of onderhoudsafspraak",
    ],
    faqs: [
      {
        q: "Kunnen jullie een onderhoudsplan maken?",
        a: "Ja. We inspecteren het pand en maken een overzicht van wat wanneer nodig is. Voor VvE's kan dat de basis zijn voor een meerjarenonderhoudsplan.",
      },
      {
        q: "Doen jullie ook kleine klussen?",
        a: "Ja. Ook één kitvoeg of een paar dakpannen. Kleine klussen combineren we waar mogelijk met werk in dezelfde buurt.",
      },
      {
        q: "Hoe snel komen jullie bij een spoedgeval?",
        a: "Bij lekkages en stormschade proberen we zo snel mogelijk te komen om de schade te beperken. Bel of app ons direct.",
      },
    ],
    related: [DG, BKT, "/zakelijk"],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust", "kitwerk-vervangen-wanneer-en-waarom"],
  },

  // ---------------------------------------------------------------- Dak en gevel
  {
    path: DG,
    name: "Dak- en gevelonderhoud",
    short: "Inspectie, pannen, goten, voegwerk, impregneren en schilderwerk.",
    h1: "Dak- en gevelonderhoud in Zeeland",
    title: "Dak- en gevelonderhoud Zeeland",
    description:
      "Dak- en gevelonderhoud in Zeeland: inspectie, dakpannen, dakgoten, voegwerk, impregneren en schilderen. Bestand tegen wind en zout. Vraag offerte aan.",
    icon: "roof",
    intro: [
      "Aan de Zeeuwse kust krijgen daken en gevels het zwaar. Westenwind drijft regen tegen de gevel, zout uit de zeelucht trekt in het metselwerk en stormen trekken aan dakpannen en nokvorsten. Wat in het binnenland tien jaar meegaat, moet hier soms eerder worden nagekeken.",
      "Met regelmatig onderhoud houd je dat in de hand. Wij doen inspecties, vervangen dakpannen en nokvorsten, reinigen dakgoten, herstellen schoorstenen, voegwerk en scheuren, en schilderen en impregneren gevels. Ook loodwerk vervangen we, want daar ontstaan veel lekkages.",
      "Je kunt per onderdeel een klus aanvragen. Of je kiest voor een seizoensinspectie, waarbij we elk jaar dak en gevel nalopen en kleine gebreken direct oplossen. Voor VvE's en beheerders werken we met vaste afspraken en rapportages met foto's.",
    ],
    signals: [
      "Verschoven of gebroken dakpannen na een storm",
      "Overlopende of lekkende dakgoten",
      "Losse voegen of scheuren in de gevel",
      "Groene aanslag of zoutuitslag op het metselwerk",
      "Vochtplekken binnen na regen uit het westen",
    ],
    steps: [
      { t: "Inspectie", d: "Visuele inspectie van dak en gevel, met foto's van elk aandachtspunt." },
      { t: "Rapport en prioriteit", d: "Je krijgt een overzicht: wat moet nu, wat kan later." },
      { t: "Uitvoeren", d: "We voeren de gekozen werkzaamheden uit, zo veel mogelijk in één bezoek." },
      { t: "Nazorg", d: "Desgewenst plannen we een volgende inspectie in." },
    ],
    duration: "Een inspectie duurt meestal een paar uur. De meeste onderhoudsklussen zijn binnen één tot vijf dagen klaar.",
    costFactors: [
      "Aantal en soort werkzaamheden",
      "Hoogte en bereikbaarheid",
      "Steiger, ladder of hoogwerker",
      "Losse klus of onderhoudsafspraak",
    ],
    faqs: [
      {
        q: "Hoe vaak moet ik mijn dak laten controleren?",
        a: "Aan de kust adviseren we een jaarlijkse controle, bij voorkeur in het najaar voor het stormseizoen, en een extra check na zware storm.",
      },
      {
        q: "Doen jullie ook schoorstenen?",
        a: "Ja. We herstellen voegwerk, kappen en loodwerk van schoorstenen, en kunnen een ongebruikte schoorsteen afdekken of verwijderen.",
      },
      {
        q: "Kan gevelonderhoud in de winter?",
        a: "Inspecties en dakreparaties wel. Voegen, pleisteren en schilderen buiten doen we bij droog weer boven het vriespunt.",
      },
    ],
    related: [`${G}`, "/expertises/schade-herstel/storm-en-natuurschade", "/expertises/renovatie-verbouw/verduurzaming/dakrenovatie"],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust", "scheuren-in-de-gevel-wanneer-ernstig"],
  },
  {
    path: `${DG}/inspectie-en-preventief-onderhoud-seizoen`,
    name: "Inspectie & seizoensonderhoud",
    short: "Elk seizoen dak en gevel nalopen, voordat kleine gebreken groot worden.",
    h1: "Dak- en gevelinspectie en seizoensonderhoud",
    title: "Dak- en gevelinspectie, seizoensonderhoud",
    description:
      "Een jaarlijkse inspectie van dak en gevel voorkomt dure schade. Met fotorapport en kleine reparaties direct opgelost. Plan een inspectie in Zeeland.",
    icon: "shield",
    intro: [
      "De meeste schade aan daken en gevels begint klein. Eén verschoven dakpan, een stuk lood dat loskomt, een dakgoot vol bladeren. Je ziet het vanaf de straat niet, totdat er water binnenkomt. Een periodieke inspectie vangt dat op tijd af.",
      "Bij een seizoensinspectie lopen we het dak en de gevel systematisch na. We kijken naar pannen en nokvorsten, lood en aansluitingen, goten en afvoeren, schoorsteen, voegwerk, pleisterwerk, kitwerk rond kozijnen en de staat van het schilderwerk. Je krijgt een kort rapport met foto's en een advies per punt.",
      "Kleine gebreken lossen we waar mogelijk direct op. Grotere punten zetten we in een prioriteitenlijst, zodat je kunt plannen en budgetteren.",
    ],
    signals: [
      "Je dak is al jaren niet bekeken",
      "Je woont aan de kust of op een open locatie",
      "Je beheert meerdere panden of een VvE",
      "Je wilt verrassingen bij een verkoop voorkomen",
    ],
    steps: [
      { t: "Afspraak", d: "We plannen de inspectie, bij voorkeur in voorjaar en najaar." },
      { t: "Inspectie", d: "Systematische controle van dak en gevel, met foto's." },
      { t: "Kleine reparaties", d: "Losse pannen, een stukje kit of een verstopte goot doen we direct." },
      { t: "Rapport", d: "Overzicht met prioriteiten: nu, binnen een jaar, later." },
    ],
    sections: [
      {
        h2: "Waarom voorjaar en najaar?",
        body: [
          "In het najaar bereid je het huis voor op stormen en regen: goten leeg, pannen vast, lood in orde. In het voorjaar zie je wat de winter heeft gedaan, zoals vorstschade aan voegen en pleister. Twee momenten, twee verschillende soorten schade.",
        ],
      },
    ],
    duration: "Een inspectie van een eengezinswoning duurt één tot drie uur, afhankelijk van bereikbaarheid.",
    costFactors: ["Grootte en hoogte van het pand", "Bereikbaarheid van het dak", "Aantal panden bij een VvE of beheerder"],
    faqs: [
      { q: "Krijg ik een rapport?", a: "Ja, een overzicht met foto's en advies per punt. Handig voor je eigen planning of voor een VvE-vergadering." },
      { q: "Moet ik thuis zijn?", a: "Voor de buitenkant niet altijd. Als we ook op zolder moeten kijken, plannen we het samen." },
      { q: "Doen jullie dit ook voor complexen?", a: "Ja. Voor VvE's en beheerders maken we afspraken per seizoen en rapporteren we per gebouw." },
    ],
    related: [DG, `${DG}/dakgoten-reinigen`, "/zakelijk"],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust", "scheuren-in-de-gevel-wanneer-ernstig"],
  },
  {
    path: `${DG}/dakpannen-en-nokvorsten-vervangen`,
    name: "Dakpannen & nokvorsten",
    short: "Gebroken pannen en losse nokvorsten vervangen, vóór het lekt.",
    h1: "Dakpannen en nokvorsten vervangen",
    title: "Dakpannen en nokvorsten vervangen",
    description:
      "Gebroken dakpannen of losse nokvorsten? We vervangen ze snel en vakkundig in Zeeland en West-Brabant, ook na stormschade. Vraag een offerte of bel direct.",
    icon: "roof",
    intro: [
      "Eén gebroken dakpan lijkt weinig, maar regen en wind krijgen daarmee vrij spel. Het water loopt langs het dakbeschot naar binnen en zorgt voor rot en vochtplekken. Nokvorsten zijn nog kwetsbaarder. Ze liggen op het hoogste punt en vangen de meeste wind. Als de specie verweert, gaan ze schuiven of waaien ze los.",
      "Wij vervangen gebroken en poreuze dakpannen door passende exemplaren en leggen verschoven pannen terug. Nokvorsten zetten we opnieuw vast, gemorteld of met een droog nokvorstsysteem met klemmen. Dat laatste is in winderige kustgebieden vaak de betere keuze.",
      "Het lastigste is soms het vinden van een passende pan bij een ouder dak. We zoeken naar hetzelfde model of een goed alternatief, en gebruiken waar mogelijk pannen van een minder zichtbaar dakvlak.",
    ],
    signals: [
      "Gebroken of verschoven pannen zichtbaar vanaf de straat",
      "Stukjes specie of pan in de dakgoot",
      "Nokvorsten die scheef liggen",
      "Vochtplekken op zolder na regen",
    ],
    steps: [
      { t: "Inspectie", d: "We bekijken het dak en zoeken passende vervangende pannen." },
      { t: "Vervangen", d: "Gebroken pannen eruit, nieuwe erin, verschoven pannen terugleggen." },
      { t: "Nokvorsten", d: "Oude specie verwijderen, nokvorsten opnieuw vastzetten of droog bevestigen." },
      { t: "Controle", d: "Aansluitingen nalopen en het dak schoon achterlaten." },
    ],
    duration: "Vaak binnen een halve tot één dag klaar.",
    costFactors: ["Aantal pannen en nokvorsten", "Beschikbaarheid van passende pannen", "Hoogte en bereikbaarheid"],
    faqs: [
      { q: "Gemorteld of droog nokvorsten?", a: "Droge systemen met klemmen en een flexibele onderstrook bewegen mee en scheuren niet. Aan de kust raden we die vaak aan." },
      { q: "Mijn pannen worden niet meer gemaakt. Wat nu?", a: "We zoeken een gelijkend model of gebruiken pannen van een minder zichtbaar dakvlak." },
      { q: "Valt dit onder mijn verzekering?", a: "Stormschade vaak wel, slijtage meestal niet. Wij leveren foto's en een omschrijving voor je verzekeraar." },
    ],
    related: [DG, "/expertises/schade-herstel/storm-en-natuurschade", "/expertises/renovatie-verbouw/verduurzaming/dakrenovatie"],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust"],
  },
  {
    path: `${DG}/schoorsteenrenovatie`,
    name: "Schoorsteenrenovatie",
    short: "Voegwerk, kap en lood van je schoorsteen weer waterdicht.",
    h1: "Schoorsteenrenovatie in Zeeland",
    title: "Schoorsteenrenovatie Zeeland",
    description:
      "Lekt je schoorsteen of brokkelt het voegwerk af? We renoveren schoorstenen: voegwerk, kap, loodwerk of afdekken. In Zeeland en Brabant. Vraag offerte aan.",
    icon: "building",
    intro: [
      "Een schoorsteen steekt boven het dak uit en staat aan alle kanten bloot aan weer en wind. Het voegwerk verweert, de kap scheurt en het lood rondom gaat los. Veel lekkages op zolder komen niet van de pannen, maar van de schoorsteen.",
      "Bij een schoorsteenrenovatie herstellen we het voegwerk of metselen we de bovenkant opnieuw op. We vervangen de afdekplaat of kap en vernieuwen het loodwerk waar de schoorsteen door het dak gaat. Gebruik je de schoorsteen niet meer, dan kunnen we hem afdekken met ventilatie, of tot onder de dakpannen verwijderen.",
      "Een ongebruikte schoorsteen die je dichtmaakt, moet wel blijven ventileren. Anders ontstaat er condens in het kanaal en zie je binnen vochtplekken op de schoorsteenmantel.",
    ],
    signals: [
      "Losse of uitgesleten voegen",
      "Vochtplekken op de schoorsteenmantel of zolder",
      "Gescheurde of ontbrekende afdekking",
      "Loodslabben die loszitten",
    ],
    steps: [
      { t: "Inspectie", d: "We bekijken metselwerk, afdekking en lood van dichtbij." },
      { t: "Advies", d: "Herstellen, opnieuw opmetselen, afdekken of verwijderen." },
      { t: "Uitvoeren", d: "Voegwerk, metselwerk, nieuwe kap en loodwerk." },
      { t: "Afronding", d: "Controle van de aansluiting op het dak en opruimen." },
    ],
    sections: [{ h2: "Let op bij schoorstenen aan de kust", body: ["Schoorstenen op Walcheren en Schouwen staan vol in de westenwind. Het metselwerk aan de windzijde verweert daardoor sneller dan de rest. Zout uit de zeelucht trekt in de voegen en kristalliseert daar. We gebruiken daarom een voegmortel die zachter is dan de steen en goed tegen zout kan, en we controleren de bevestiging van de kap extra. Een schoorsteen die je niet meer gebruikt, laten we bij voorkeur ventileren via een afdekkap met roosters, zodat er geen condens in het kanaal ontstaat."] }],
    duration: "Meestal één tot drie werkdagen, afhankelijk van de omvang.",
    costFactors: ["Hoogte en bereikbaarheid", "Omvang van het metselwerk", "Nieuw lood of loodvervanger"],
    faqs: [
      { q: "Moet een ongebruikte schoorsteen weg?", a: "Niet per se. Afdekken met ventilatie is vaak genoeg. Verwijderen kan ook en voorkomt toekomstig onderhoud." },
      { q: "Doen jullie ook rookkanalen?", a: "Nee, voor het vegen en inspecteren van rookkanalen verwijzen we naar een erkende schoorsteenveger." },
      { q: "Is lood beter dan loodvervanger?", a: "Lood gaat lang mee en is goed te vormen. Loodvervanger is lichter en heeft geen nadelen voor afstromend water. We adviseren per situatie." },
    ],
    related: [`${DG}/loodwerk-vervangen`, DG, "/expertises/schade-herstel/lekkages-vochtproblemen"],
    articles: ["vochtige-muren-oorzaken-en-oplossingen"],
  },
  {
    path: `${DG}/dakgoten-reinigen`,
    name: "Dakgoten reinigen",
    short: "Vrije goten en afvoeren, zodat regenwater weg kan.",
    h1: "Dakgoten reinigen en herstellen",
    title: "Dakgoten reinigen en herstellen",
    description:
      "Overlopende dakgoot? We reinigen dakgoten en regenpijpen, herstellen lekkende naden en voorkomen een natte gevel. In Zeeland en Brabant. Plan een afspraak.",
    icon: "drop",
    intro: [
      "Een dakgoot vol bladeren, mos en zand loopt bij de eerste stevige bui over. Het water klettert dan langs de gevel, trekt in het metselwerk en kan binnen vochtplekken geven. Ook houten gootbakken gaan rotten als er steeds water in blijft staan.",
      "We reinigen dakgoten en regenpijpen, controleren de afvoer en herstellen lekkende naden en hoeken. Bij zinken goten kijken we naar soldeernaden en roest, bij houten goten naar de bekleding en het hout eronder.",
      "In Zeeland en West-Brabant, met veel bomen in oudere wijken, is reinigen in het najaar een vaste prik. Combineer het met een dakinspectie, dan is de ladder of hoogwerker meteen goed gebruikt.",
    ],
    signals: [
      "Water dat over de rand van de goot loopt",
      "Planten of mos die uit de goot groeien",
      "Natte plekken op de gevel onder de goot",
      "Druppelende naden of hoeken",
    ],
    steps: [
      { t: "Reinigen", d: "Bladeren, mos en slib uit de goot halen." },
      { t: "Doorspoelen", d: "Afvoeren en regenpijpen doorspoelen en controleren." },
      { t: "Herstellen", d: "Lekkende naden solderen of afdichten, gootbeugels vastzetten." },
      { t: "Advies", d: "Eventueel bladvangers of vervanging van versleten goten." },
    ],
    sections: [{ h2: "Zinken, houten of kunststof goten", body: ["Elk type goot vraagt om andere aandacht. Zinken goten gaan lang mee, maar de soldeernaden en de hoeken kunnen gaan lekken. Bij houten gootbakken met een zinken of kunststof bekleding zit het risico in het hout eronder: blijft daar water staan, dan gaat het rotten. Kunststof goten zijn licht en goedkoop, maar kunnen bij vorst en zon scheuren. Bij het reinigen kijken we daarom altijd ook naar de staat van de goot zelf en de beugels."] }],
    duration: "Voor een gemiddelde woning een paar uur.",
    costFactors: ["Lengte van de goten", "Hoogte en bereikbaarheid", "Herstelwerk aan naden of goot"],
    faqs: [
      { q: "Hoe vaak moeten goten schoon?", a: "Minimaal één keer per jaar, in het najaar. Bij veel bomen in de buurt twee keer." },
      { q: "Helpen bladvangers?", a: "Ja, ze verminderen vervuiling, maar vervangen het reinigen niet helemaal." },
      { q: "Repareren jullie ook zinken goten?", a: "Ja, kleine lekkages solderen we. Is de goot op, dan vervangen we hem." },
    ],
    related: [`${DG}/inspectie-en-preventief-onderhoud-seizoen`, DG, "/expertises/schade-herstel/lekkages-vochtproblemen"],
    articles: ["vochtige-muren-oorzaken-en-oplossingen"],
  },
  {
    path: `${DG}/impregneren-coaten`,
    name: "Impregneren & coaten",
    short: "Een onzichtbare laag die regen buiten houdt en de muur laat ademen.",
    h1: "Gevel impregneren en coaten in Zeeland",
    title: "Gevel impregneren en coaten Zeeland",
    description:
      "Gevel impregneren tegen slagregen en zout? We maken metselwerk waterafstotend en dampopen. Ideaal aan de Zeeuwse kust. Vraag een vrijblijvende offerte aan.",
    icon: "shield",
    intro: [
      "Baksteen en voegen nemen water op. Bij slagregen kan een gevel aan de westkant behoorlijk nat worden. Dat vocht trekt naar binnen, maakt de muur koud en neemt zouten mee. Bij vorst kan het water in de steen uitzetten en stukjes eraf drukken.",
      "Met een hydrofobeermiddel, ook wel impregneermiddel, maak je de gevel waterafstotend. Het middel trekt in de steen en vormt geen laag erop. De gevel ziet er hetzelfde uit en kan vocht van binnen nog steeds kwijt. Een coating is een dunne, vaak gekleurde laag die meer bescherming biedt, maar het uiterlijk verandert.",
      "Impregneren werkt alleen op een gezonde gevel. Scheuren en losse voegen moeten eerst hersteld worden, en de muur moet droog zijn. Anders sluit je vocht in. Daarom beginnen we altijd met een inspectie en een vochtmeting.",
    ],
    signals: [
      "Natte plekken binnen na regen uit het westen",
      "Groene aanslag op de gevel",
      "Witte zoutuitslag op het metselwerk",
      "Een gevel die lang nat blijft na regen",
    ],
    steps: [
      { t: "Inspectie en vochtmeting", d: "Is de gevel gezond en droog genoeg?" },
      { t: "Herstel", d: "Voegen, scheuren en kitwerk eerst op orde." },
      { t: "Reinigen", d: "Groene aanslag en vuil verwijderen, daarna laten drogen." },
      { t: "Aanbrengen", d: "Impregneermiddel verzadigend aanbrengen, ramen en kozijnen afgeschermd." },
    ],
    duration: "Voor een eengezinswoning één tot twee dagen, plus droogtijd na reiniging.",
    costFactors: ["Geveloppervlak", "Benodigd herstel vooraf", "Type middel of coating"],
    faqs: [
      { q: "Hoe lang werkt een impregnering?", a: "Dat verschilt per middel en ligging. Op de verpakking en in de offerte staat de verwachte werkingsduur van het gekozen product." },
      { q: "Verandert de kleur van mijn gevel?", a: "Een impregnering is kleurloos. Bij sommige stenen wordt de kleur iets dieper. We testen eerst op een klein stuk." },
      { q: "Kan het op een gepleisterde gevel?", a: "Ja, met een middel dat geschikt is voor pleisterwerk. Vaak is een dampopen gevelverf dan de betere keuze." },
    ],
    related: [`${DG}/gevelreiniging`, `${DG}/voegwerk-herstellen-vernieuwen`, G],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust", "vochtige-muren-oorzaken-en-oplossingen"],
  },
  {
    path: `${DG}/gevelreiniging`,
    name: "Gevelreiniging",
    short: "Aanslag, vuil en zoutuitslag eraf, zonder de gevel te beschadigen.",
    h1: "Gevelreiniging in Zeeland en West-Brabant",
    title: "Gevelreiniging Zeeland en West-Brabant",
    description:
      "Groene aanslag, vuil of zoutuitslag op je gevel? We reinigen gevels zonder schade aan steen en voeg. Werkgebied Zeeland en West-Brabant. Vraag offerte aan.",
    icon: "facade",
    intro: [
      "Een vuile gevel is niet alleen lelijk. Groene aanslag houdt vocht vast en algen kunnen dieper in de voeg trekken. Witte zoutuitslag laat zien dat er water door de muur beweegt. Reinigen geeft de gevel zijn kleur terug en laat zien in welke staat het metselwerk echt is.",
      "We kiezen de methode op basis van steen, voeg en vervuiling. Een zachte, oude baksteen verdraagt geen hogedrukreiniger. Daar werken we met lage druk, warm water of een stoomreiniger, en met een middel tegen groene aanslag. Hardere gevels kunnen soms wat meer hebben.",
      "Na het reinigen beoordelen we de voegen en de steen. Vaak is dit het moment om voegwerk te herstellen of de gevel te impregneren.",
    ],
    signals: [
      "Groene of zwarte aanslag op de noordgevel",
      "Witte zoutuitslag",
      "Een grauwe, vuile gevel",
      "Voorbereiding op voegwerk of impregneren",
    ],
    steps: [
      { t: "Proefvlak", d: "We testen de methode op een klein stuk." },
      { t: "Afschermen", d: "Ramen, kozijnen, planten en bestrating beschermen." },
      { t: "Reinigen", d: "Met de gekozen methode, van boven naar beneden." },
      { t: "Nabehandeling", d: "Eventueel een middel tegen nieuwe aanslag en advies over voegwerk." },
    ],
    sections: [{ h2: "Reinigen in beschermd stadsgezicht", body: ["In de binnensteden van Middelburg, Veere en Zierikzee staan veel monumenten. Daar werken we met de zachtste methode die het vuil nog verwijdert, en altijd eerst op een proefvlak. Een te agressieve reiniging kan de bakhuid van oude stenen beschadigen. Die laag beschermt de steen tegen water. Is hij eenmaal weg, dan neemt de steen veel meer vocht op en verweert hij sneller."] }],
    duration: "Een eengezinswoning is meestal in één tot twee dagen gereinigd.",
    costFactors: ["Geveloppervlak", "Soort vervuiling", "Reinigingsmethode", "Hoogte en bereikbaarheid"],
    faqs: [
      { q: "Is hogedruk slecht voor mijn gevel?", a: "Bij zachte steen en oude voegen wel. Dan spoel je het oppervlak weg. Wij kiezen altijd een methode die past bij de gevel." },
      { q: "Komt de groene aanslag terug?", a: "Op schaduwrijke gevels op den duur wel. Een nabehandeling en impregnering vertragen dat flink." },
      { q: "Wat doe je tegen zoutuitslag?", a: "Droog afborstelen, niet nat maken. En de oorzaak van het vocht aanpakken." },
    ],
    related: [`${DG}/impregneren-coaten`, `${DG}/voegwerk-herstellen-vernieuwen`, `${DG}/gevel-schilderen`],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust"],
  },
  {
    path: `${DG}/scheuren-herstellen`,
    name: "Scheuren herstellen",
    short: "Eerst de oorzaak, dan een herstel dat blijft zitten.",
    h1: "Scheuren in de gevel herstellen",
    title: "Scheuren in de gevel herstellen",
    description:
      "Scheuren in je gevel of muur? We zoeken de oorzaak en herstellen duurzaam, met wapening of injectie waar nodig. Zeeland en Amsterdam. Vraag offerte aan.",
    icon: "crack",
    intro: [
      "Een scheur in de gevel kan onschuldig zijn, of een teken van een groter probleem. Haarscheurtjes in pleisterwerk ontstaan vaak door krimp. Een trapvormige scheur door het metselwerk wijst eerder op zetting van de fundering. Een horizontale scheur bij een latei of balk kan op roest of doorbuiging duiden.",
      "Daarom beginnen we met de oorzaak. We kijken naar het patroon, de breedte en de plek van de scheur, en of hij nog groeit. Pas daarna kiezen we het herstel: uitslijpen en opnieuw voegen, wapenen met RVS-staven in de lintvoeg, injecteren of het pleisterwerk opnieuw opzetten met wapening.",
      "Bij twijfel over de constructie of de fundering adviseren we om een constructeur te laten kijken. Een scheur dichtsmeren zonder de oorzaak te kennen, lost niets op. Dan zit hij er binnen een paar jaar weer.",
    ],
    signals: [
      "Trapvormige scheuren in metselwerk",
      "Scheuren boven ramen of deuren",
      "Haarscheuren in gevelpleister",
      "Scheuren die breder worden",
      "Ramen of deuren die gaan klemmen",
    ],
    steps: [
      { t: "Analyse", d: "Patroon, breedte en oorzaak bepalen. Zo nodig scheurmeters plaatsen." },
      { t: "Advies", d: "Herstel, wapening, injectie of eerst een constructeur." },
      { t: "Herstel", d: "Uitslijpen, wapenen, injecteren en opnieuw voegen of pleisteren." },
      { t: "Afwerken", d: "Kleur en structuur zo goed mogelijk laten aansluiten op de rest." },
    ],
    duration: "De meeste scheurherstellingen zijn in één tot drie dagen klaar.",
    costFactors: ["Lengte en aantal scheuren", "Herstelmethode", "Hoogte en bereikbaarheid"],
    faqs: [
      { q: "Wanneer is een scheur gevaarlijk?", a: "Als hij breder wordt dan een paar millimeter, groeit, of samengaat met klemmende deuren en ramen. Lees ons artikel over scheuren in de gevel." },
      { q: "Kun je een scheur onzichtbaar maken?", a: "Bijna. Bij metselwerk zoeken we passende voegmortel, bij pleisterwerk werken we het vlak bij." },
      { q: "Moet er een constructeur bij?", a: "Bij zettingsscheuren of twijfel over de constructie wel. Wij adviseren je daarin eerlijk." },
    ],
    related: ["/expertises/schade-herstel/balkon-en-gevelschade", `${DG}/voegwerk-herstellen-vernieuwen`, `${G}/buiten-stucwerk`],
    articles: ["scheuren-in-de-gevel-wanneer-ernstig"],
  },
  {
    path: `${DG}/voegwerk-herstellen-vernieuwen`,
    name: "Voegwerk",
    short: "Losse en verweerde voegen uithakken en opnieuw voegen.",
    h1: "Voegwerk herstellen en vernieuwen",
    title: "Voegwerk herstellen en vernieuwen",
    description:
      "Losse of verweerde voegen? We hakken voegwerk uit en voegen opnieuw met de juiste mortel, passend bij steen en pand. Zeeland en Brabant. Vraag offerte aan.",
    icon: "layers",
    intro: [
      "Voegen zijn de zwakke plek van een bakstenen gevel. Ze verweren door regen, vorst en zout. Als ze zacht worden of loslaten, kan water de muur in. Dan krijg je vochtplekken binnen, vorstschade aan de stenen en soms zelfs losse stenen.",
      "Bij voegwerk herstellen hakken of slijpen we de oude voeg tot de juiste diepte uit en brengen we nieuwe mortel aan. De keuze van mortel is belangrijk. De voeg moet zachter zijn dan de steen, zodat de steen niet gaat scheuren. Bij oude panden kiezen we daarom vaak een kalkmortel.",
      "Ook het voegprofiel bepaalt het beeld: platvol, terugliggend, gesneden of knipvoeg. We stemmen het profiel en de kleur af op het pand, zodat het herstel niet opvalt.",
    ],
    signals: [
      "Voegen die zacht zijn of verkruimelen",
      "Gaten tussen de stenen",
      "Vochtplekken binnen na regen",
      "Losse of beschadigde stenen",
    ],
    steps: [
      { t: "Beoordelen", d: "Hardheid, kleur en profiel van de bestaande voeg vaststellen." },
      { t: "Uithakken", d: "Oude voeg verwijderen tot de juiste diepte, stof uitblazen." },
      { t: "Voegen", d: "Voorbevochtigen en nieuwe mortel in de juiste kleur en het juiste profiel aanbrengen." },
      { t: "Nazorg", d: "Nat houden bij warm weer en de gevel schoon opleveren." },
    ],
    duration: "Een complete gevel van een eengezinswoning kost meestal één tot twee weken.",
    costFactors: ["Aantal vierkante meters", "Hardheid van de oude voeg", "Voegprofiel en mortel", "Steiger"],
    faqs: [
      { q: "Kan ik alleen de slechte delen laten herstellen?", a: "Ja. Plaatselijk herstel kan prima, zolang kleur en profiel aansluiten." },
      { q: "Waarom kalkmortel bij oude panden?", a: "Kalkmortel is zachter en dampopener. Een harde cementvoeg in zachte steen laat de steen kapotvriezen." },
      { q: "Wanneer kan voegwerk niet?", a: "Bij vorst, harde regen of felle zon op de gevel. We plannen het in het voorjaar tot de vroege herfst." },
    ],
    related: [`${DG}/gevelreiniging`, `${DG}/impregneren-coaten`, `${DG}/scheuren-herstellen`],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust", "scheuren-in-de-gevel-wanneer-ernstig"],
  },
  {
    path: `${DG}/gevel-schilderen`,
    name: "Gevel schilderen",
    short: "Dampopen gevelverf op pleister- of metselwerk.",
    h1: "Gevel schilderen in Zeeland en Amsterdam",
    title: "Gevel schilderen Zeeland en Amsterdam",
    description:
      "Gevel laten schilderen? We behandelen de ondergrond en schilderen met dampopen gevelverf die zout en wind aankan. Zeeland en Amsterdam. Vraag offerte aan.",
    icon: "paint",
    intro: [
      "Een geschilderde gevel geeft een huis een frisse, rustige uitstraling. Maar verf op een muur is meer dan kleur. Een verkeerde verf sluit vocht in de muur op. Dat zie je later terug als blazen, afbladderen en vochtplekken binnen.",
      "Wij schilderen gevels met dampopen gevelverf, zoals silicaat- of siliconenharsverf. Die houdt regen buiten en laat waterdamp van binnen ontsnappen. Op oude kalkpleister kiezen we vaak een kalk- of silicaatverf, die goed bij de ondergrond past.",
      "De voorbereiding is het halve werk. We verwijderen losse verf, herstellen scheuren en pleister, reinigen de gevel en brengen een passende grondlaag aan. Pas dan schilderen we, in twee lagen.",
    ],
    signals: [
      "Afbladderende of krijtende verf",
      "Blazen in de verflaag",
      "Een verkleurde of vlekkerige gevel",
      "Je wilt een andere kleur",
    ],
    steps: [
      { t: "Ondergrond beoordelen", d: "Hecht de oude verf? Is de gevel droog?" },
      { t: "Voorbereiden", d: "Losse verf verwijderen, herstellen en reinigen." },
      { t: "Gronden", d: "Een grondlaag passend bij ondergrond en verfsysteem." },
      { t: "Schilderen", d: "Twee lagen dampopen gevelverf." },
    ],
    sections: [{ h2: "Welke verf voor welke gevel?", body: ["Silicaatverf hecht chemisch aan minerale ondergronden zoals kalkpleister en baksteen en blijft zeer dampopen. Siliconenharsverf is sterk waterafstotend en geschikt voor de meeste pleisters. Acrylaatverf is minder dampopen en gebruiken we alleen waar de ondergrond dat toelaat. Op een gevel die al eerder met een dichte verf is geschilderd, beoordelen we eerst of die laag eraf moet."] }],
    duration: "Een eengezinswoning is meestal in één week klaar, afhankelijk van het weer.",
    costFactors: ["Geveloppervlak", "Staat van de oude verflaag", "Verfsysteem", "Steiger"],
    faqs: [
      { q: "Kan ik baksteen schilderen?", a: "Ja, maar het is moeilijk terug te draaien. Zorg dat de gevel droog en gezond is, en kies een dampopen verf." },
      { q: "Mag ik zomaar een andere kleur kiezen?", a: "Meestal wel. In beschermd stadsgezicht of bij monumenten kan de gemeente regels stellen." },
      { q: "Hoe vaak moet een gevel geschilderd?", a: "Dat hangt af van verf, ligging en klimaat. Aan de kust vaker dan landinwaarts." },
    ],
    related: [`${G}/buiten-stucwerk`, `${DG}/gevelreiniging`, `${DG}/scheuren-herstellen`],
    articles: ["zout-en-wind-gevelonderhoud-zeeuwse-kust"],
  },
  {
    path: `${DG}/loodwerk-vervangen`,
    name: "Loodwerk vervangen",
    short: "Waterdichte aansluitingen bij schoorsteen, dakkapel en muur.",
    h1: "Loodwerk vervangen en herstellen",
    title: "Loodwerk vervangen en herstellen",
    description:
      "Lekkage bij schoorsteen of dakkapel? Vaak zit het in het loodwerk. We vervangen lood of loodvervanger vakkundig in Zeeland en Brabant. Vraag offerte aan.",
    icon: "roof",
    intro: [
      "Lood zit overal waar het dak ergens tegenaan komt: bij de schoorsteen, de dakkapel, een opgaande muur of een dakraam. Het vormt de waterdichte overgang tussen twee bouwdelen. Als het lood scheurt, loslaat of verkeerd is aangebracht, loopt het water precies daar naar binnen.",
      "Lood zet uit en krimpt met de temperatuur. Te grote stukken of te stijf vastgezet lood gaat daardoor scheuren. Ook harde wind kan lood oplichten, zodat regen eronder waait. Aan de kust zien we dat regelmatig.",
      "We vervangen loodwerk met de juiste maten, overlappen en bevestiging. Waar dat beter past, gebruiken we loodvervanger, een lichter materiaal dat geen lood afgeeft aan het regenwater.",
    ],
    signals: [
      "Lekkage bij schoorsteen, dakkapel of dakraam",
      "Opgekruld of gescheurd lood",
      "Loodslabben die loszitten in de voeg",
      "Vochtplekken langs een opgaande muur",
    ],
    steps: [
      { t: "Lokaliseren", d: "We zoeken waar het water precies binnenkomt." },
      { t: "Verwijderen", d: "Oud lood eraf en de ondergrond controleren." },
      { t: "Aanbrengen", d: "Nieuw lood of loodvervanger op maat, met de juiste overlap." },
      { t: "Vastzetten", d: "Inslijpen in de voeg, vastzetten en afkitten waar nodig." },
    ],
    sections: [{ h2: "Waar lekt loodwerk het vaakst?", body: ["De meeste lekkages zien we bij de onderkant van een schoorsteen, aan de bovenzijde waar water tegen de schoorsteen stuwt, en langs de wangen van dakkapellen. Ook loketten en slabben die te kort zijn, of zonder voldoende overlap op de pannen liggen, laten bij harde wind water door. Bij het vervangen controleren we daarom ook de maatvoering en de bevestiging in de voeg."] }],
    duration: "Meestal binnen één dag.",
    costFactors: ["Hoeveelheid lood", "Lood of loodvervanger", "Bereikbaarheid"],
    faqs: [
      { q: "Is lood schadelijk?", a: "Lood in contact met regenwater geeft kleine hoeveelheden lood af. Daarom kiezen we bij nieuw werk steeds vaker loodvervanger." },
      { q: "Hoe lang gaat lood mee?", a: "Goed aangebracht lood gaat tientallen jaren mee. De meeste problemen komen door verkeerde maatvoering of bevestiging." },
      { q: "Kan ik het met kit dichtmaken?", a: "Als noodoplossing even, maar kit veroudert snel in de zon. Herstel het lood zelf." },
    ],
    related: [`${DG}/schoorsteenrenovatie`, "/expertises/schade-herstel/lekkages-vochtproblemen", `${DG}/dakpannen-en-nokvorsten-vervangen`],
    articles: ["vochtige-muren-oorzaken-en-oplossingen"],
  },

  // ---------------------------------------------------------------- Balkon
  {
    path: B,
    name: "Balkononderhoud",
    short: "Waterdichting en kitwerk van balkons en galerijen.",
    h1: "Balkononderhoud: waterdichting en kitwerk",
    title: "Balkononderhoud en waterdichting",
    description:
      "Balkononderhoud voor particulier en VvE: waterdichting controleren, kitwerk vervangen en lekkages naar de onderburen voorkomen. Vraag een offerte aan.",
    icon: "balcony",
    intro: [
      "Een balkon staat het hele jaar in weer en wind. Regenwater moet snel weg naar de afvoer. Als de waterdichting slijt of de kitvoegen bij de gevel loslaten, loopt het water de constructie in. Dan zie je roestplekken, afgebroken beton of lekkages bij de onderburen.",
      "Wij controleren en herstellen de waterdichting van balkons en galerijen. We vervangen kitwerk, herstellen of vernieuwen de coating en zorgen dat het afschot en de afvoer kloppen. Bij beton- en gevelschade aan balkons kun je ook bij ons terecht.",
      "Veel van ons balkonwerk doen we voor VvE's in appartementencomplexen, in Zeeland en in Amsterdam. Daar is periodiek onderhoud de goedkoopste manier om grote betonreparaties te voorkomen.",
    ],
    signals: [
      "Plassen water die blijven staan",
      "Scheuren in de coating of tegels",
      "Losse kitvoegen bij gevel en deur",
      "Lekkage of roestplekken bij de onderburen",
    ],
    sections: [{ h2: "Periodiek balkononderhoud voor VvE's", body: ["Voor appartementencomplexen raden we een vaste inspectieronde aan. We lopen alle balkons en galerijen na, maken foto's en zetten de bevindingen per balkon in een overzicht. Kleine punten, zoals een losse kitvoeg, lossen we direct op. Grotere punten krijgen een prioriteit, zodat het VvE-bestuur kan plannen en budgetteren. Zo voorkom je dat kleine gebreken uitgroeien tot betonrot en dure reparaties."] }],
    duration: "Kitwerk en coatingherstel op één balkon is vaak binnen één tot twee dagen klaar.",
    costFactors: ["Aantal en grootte van balkons", "Staat van de ondergrond", "Coating of tegelwerk"],
    faqs: [
      { q: "Wie betaalt balkononderhoud in een VvE?", a: "Dat staat in de splitsingsakte. Vaak is het balkon gemeenschappelijk en betaalt de VvE." },
      { q: "Hoe vaak moet een balkon gecontroleerd?", a: "We adviseren een jaarlijkse controle, en kitwerk na een aantal jaar te vervangen." },
      { q: "Doen jullie ook betonreparaties?", a: "Ja, kleine betonreparaties doen we zelf. Zie balkon- en gevelschade." },
    ],
    related: ["/expertises/schade-herstel/balkon-en-gevelschade", "/zakelijk", `${BKT}/voeg-en-kitwerk-vervangen`],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },
  {
    path: `${B}/controle-en-onderhoud-van-waterdichting`,
    name: "Waterdichting balkon",
    short: "Coating, afschot en afvoer controleren en herstellen.",
    h1: "Waterdichting van balkons controleren en herstellen",
    title: "Waterdichting balkon controleren",
    description:
      "Lekt je balkon naar de onderburen? We controleren en herstellen waterdichting, coating en afvoer van balkons en galerijen. Voor particulier en VvE.",
    icon: "balcony",
    intro: [
      "De waterdichting van een balkon is meestal een coating, een bitumineuze laag of een kunststof membraan onder de tegels. Je ziet hem niet altijd, maar hij doet het belangrijkste werk. Als hij scheurt of loslaat, trekt water in het beton. Het wapeningsstaal gaat roesten, zet uit en drukt het beton kapot.",
      "Bij een controle kijken we naar scheuren, blazen en loslatende delen in de coating, naar het afschot en naar de afvoer. Ook de randen bij de gevel en de deurdorpel zijn kwetsbaar. Daar zit vaak het lek.",
      "Kleine schade herstellen we plaatselijk. Is de coating aan het einde van zijn levensduur, dan brengen we een nieuw systeem aan. Daarbij zorgen we dat het water weer goed wegloopt.",
    ],
    signals: [
      "Plassen die lang blijven staan",
      "Scheuren of blazen in de coating",
      "Lekkage bij de onderburen",
      "Roestplekken of afgebrokkeld beton aan de onderkant",
    ],
    steps: [
      { t: "Controle", d: "Coating, afschot, afvoer en randen bekijken." },
      { t: "Voorbereiden", d: "Reinigen, losse delen verwijderen, schuren." },
      { t: "Herstellen", d: "Plaatselijk herstel of een nieuw coatingsysteem in lagen." },
      { t: "Afwerken", d: "Randen en dorpels afdichten, afvoer controleren." },
    ],
    sections: [{ h2: "Afschot en afvoer: het water moet weg", body: ["Een waterdichting werkt alleen goed als het water snel van het balkon wegloopt. Te weinig afschot of een verstopte uitloop zorgt voor plassen die dagen blijven staan. Dat belast de coating en de randen extra. Bij de controle meten we daarom ook het afschot en spoelen we de afvoer door. Waar nodig passen we de uitloop aan of maken we een extra noodoverloop."] }],
    duration: "Eén tot drie dagen per balkon, afhankelijk van het systeem en de droogtijd.",
    costFactors: ["Oppervlak", "Plaatselijk herstel of nieuw systeem", "Betonschade"],
    faqs: [
      { q: "Kan ik het balkon gebruiken tijdens het werk?", a: "Niet tijdens het aanbrengen en drogen van de coating. Meestal gaat het om een paar dagen." },
      { q: "Moeten de tegels eraf?", a: "Als de waterdichting onder de tegels zit en lekt, vaak wel. We onderzoeken eerst waar het lek zit." },
      { q: "Werken jullie voor VvE's?", a: "Ja, we doen complete complexen en rapporteren per balkon." },
    ],
    related: [`${B}/kitwerk-vervangen`, "/expertises/schade-herstel/balkon-en-gevelschade", "/zakelijk"],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },
  {
    path: `${B}/kitwerk-vervangen`,
    name: "Kitwerk balkon",
    short: "Kitvoegen bij gevel, dorpel en hekwerk vervangen.",
    h1: "Kitwerk op balkons en galerijen vervangen",
    title: "Kitwerk balkon en galerij vervangen",
    description:
      "Kitvoegen op je balkon gescheurd of los? We vervangen kitwerk bij gevel, dorpel en hekwerk met UV-bestendige kit. Voor particulier en VvE. Vraag offerte.",
    icon: "balcony",
    intro: [
      "Op een balkon zitten kitvoegen op plekken waar verschillende materialen samenkomen: bij de gevel, de deurdorpel, de hekwerkbevestiging en de dilatatievoegen. Die voegen vangen beweging op. Door zon, vorst en beweging droogt kit na een aantal jaar uit en laat los.",
      "Een losgelaten kitvoeg is een directe ingang voor water. Bij balkons loopt dat water de vloer of de gevel in. Vaak zie je het pas als de onderburen een lekkage melden.",
      "We verwijderen de oude kit volledig, maken de voeg schoon en vetvrij, brengen waar nodig een rugvulling en primer aan, en kitten opnieuw met een UV-bestendige kit die bij de materialen past.",
    ],
    signals: [
      "Gescheurde of uitgedroogde kitvoegen",
      "Kit die loslaat van de ondergrond",
      "Zwarte schimmel in de voeg",
      "Lekkage bij de onderburen",
    ],
    steps: [
      { t: "Verwijderen", d: "Oude kit er volledig uit, ook de resten." },
      { t: "Voorbereiden", d: "Reinigen, ontvetten, rugvulling en primer." },
      { t: "Kitten", d: "Nieuwe kit in de juiste breedte en diepte." },
      { t: "Afwerken", d: "Strak afgestreken en schoon opgeleverd." },
    ],
    sections: [{ h2: "Kitwerk op galerijen en in trappenhuizen", body: ["Naast balkons zitten ook op galerijen, bij voordeurkozijnen en in trappenhuizen veel kitvoegen die water moeten tegenhouden. Bij complexen nemen we die vaak in één ronde mee. Dat scheelt opstartkosten en de bewoners hebben maar één keer overlast. We noteren per woning welke voegen zijn vervangen, zodat je weet wanneer de volgende ronde nodig is."] }],
    duration: "Vaak binnen een dag, ook bij meerdere balkons in een complex.",
    costFactors: ["Aantal strekkende meters", "Bereikbaarheid", "Type kit"],
    faqs: [
      { q: "Hoe lang gaat kit mee?", a: "Buiten meestal enkele jaren tot ruim tien jaar, afhankelijk van zon, beweging en kwaliteit." },
      { q: "Kan nieuwe kit over oude kit?", a: "Nee. Nieuwe kit hecht niet goed op oude kit. Het moet er volledig uit." },
      { q: "Welke kit gebruiken jullie?", a: "Een kit die past bij de ondergrond en de beweging, zoals een MS-polymeer of polyurethaan voor buiten." },
    ],
    related: [`${B}/controle-en-onderhoud-van-waterdichting`, `${BKT}/voeg-en-kitwerk-vervangen`, B],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },

  // ---------------------------------------------------------------- BKT
  {
    path: BKT,
    name: "Badkamer, keuken & toilet onderhoud",
    short: "Kitwerk, voegen, schimmel, tegels en sanitair in natte ruimtes.",
    h1: "Onderhoud badkamer, keuken en toilet (BKT)",
    title: "Onderhoud badkamer, keuken en toilet",
    description:
      "Onderhoud aan badkamer, keuken en toilet: kit- en voegwerk, schimmel, tegels en sanitair. Voor particulier, VvE en corporatie. Vraag een offerte aan.",
    icon: "bath",
    intro: [
      "Natte ruimtes vragen het meeste onderhoud in een huis. Water, zeep en stoom zitten elke dag aan de voegen en de kit. Na een paar jaar zie je zwarte randjes, loszittende kit of een tegel die hol klinkt. Wacht je te lang, dan loopt er water achter de tegels.",
      "Met tijdig onderhoud houd je je badkamer, keuken en toilet jaren langer goed. Wij vervangen kit- en voegwerk, pakken schimmel aan bij de bron, herstellen tegelwerk en vervangen sanitair en meubels. Zo hoeft er niet direct een complete renovatie te komen.",
      "Voor corporaties en beheerders doen we BKT-onderhoud bij mutaties en planmatig onderhoud. Snel, schoon en met een vaste werkwijze per woning.",
    ],
    signals: [
      "Zwarte schimmel in kit en voegen",
      "Loszittende kit langs bad of douche",
      "Holle of gebarsten tegels",
      "Lekkend of versleten sanitair",
    ],
    duration: "De meeste BKT-onderhoudsklussen zijn binnen één tot twee dagen klaar.",
    costFactors: ["Omvang van het werk", "Aantal ruimtes", "Materialen en sanitair"],
    faqs: [
      { q: "Wanneer is onderhoud genoeg en wanneer renoveren?", a: "Als de waterdichting en leidingen goed zijn, is onderhoud vaak genoeg. Lekt het achter de tegels, dan is renovatie verstandiger." },
      { q: "Doen jullie mutatieonderhoud voor corporaties?", a: "Ja. Kijk op de pagina Zakelijk voor onze werkwijze." },
      { q: "Kunnen jullie snel langskomen?", a: "Kleine klussen plannen we meestal op korte termijn. Bij lekkage zo snel mogelijk." },
    ],
    related: ["/expertises/renovatie-verbouw/verduurzaming/badkamer-renovatie", `${BKT}/schimmelreiniging-en-ventilatie`, "/zakelijk"],
    articles: ["kitwerk-vervangen-wanneer-en-waarom", "schimmel-in-de-badkamer-blijvend-oplossen"],
  },
  {
    path: `${BKT}/voeg-en-kitwerk-vervangen`,
    name: "Voeg- en kitwerk",
    short: "Nieuwe kit en voegen: fris, waterdicht en schimmelwerend.",
    h1: "Voeg- en kitwerk vervangen in badkamer en keuken",
    title: "Kitwerk en voegen badkamer vervangen",
    description:
      "Zwarte of loszittende kitranden in badkamer of keuken? We vervangen kit- en voegwerk schimmelwerend en waterdicht. Zeeland en Amsterdam. Vraag offerte aan.",
    icon: "bath",
    intro: [
      "Kitvoegen zitten in de hoeken van je badkamer, rond het bad, de douchebak, het toilet en langs het aanrecht. Ze vangen beweging op en houden water tegen. Na verloop van tijd verkleurt kit door schimmel en laat hij los van de tegels. Dan kan water achter de kit en de tegels lopen.",
      "Tegelvoegen nemen ook water op. Als ze poreus worden of gaan verkruimelen, krijgt vocht vrij spel. Ze worden donker en zien er vuil uit, hoe vaak je ook schoonmaakt.",
      "We verwijderen de oude kit volledig, maken de voeg schimmelvrij en droog, en kitten opnieuw met sanitairkit met schimmelwerende toevoeging. Tegelvoegen slijpen we uit en voegen we opnieuw, of we zetten ze in met een voegimpregneer.",
    ],
    signals: [
      "Zwarte kit die niet meer schoon wordt",
      "Kit die loslaat of scheurt",
      "Verkruimelende of donkere tegelvoegen",
      "Vocht in de wand achter het bad of de douche",
    ],
    steps: [
      { t: "Oude kit eruit", d: "Volledig verwijderen, inclusief resten." },
      { t: "Schimmel weg", d: "Voegen behandelen en goed laten drogen." },
      { t: "Opnieuw kitten", d: "Sanitairkit strak aanbrengen. Bij een bad vullen we het bad eerst, zodat de kit niet scheurt." },
      { t: "Voegen", d: "Waar nodig voegen uitslijpen en opnieuw voegen." },
    ],
    duration: "Kitwerk in een badkamer is meestal binnen een halve dag klaar. De kit moet daarna 24 uur uitharden.",
    costFactors: ["Aantal meters kit", "Of tegelvoegen mee moeten", "Hoeveelheid schimmel"],
    faqs: [
      { q: "Hoe vaak moet kit vervangen?", a: "In een badkamer gemiddeld elke paar jaar. Lees ons artikel over kitwerk vervangen." },
      { q: "Waarom komt schimmel steeds terug?", a: "Vaak door slechte ventilatie. Nieuwe kit helpt, maar de oorzaak zit in het vocht in de lucht." },
      { q: "Kan ik direct douchen?", a: "Wacht 24 uur, zodat de kit kan uitharden." },
    ],
    related: [`${BKT}/schimmelreiniging-en-ventilatie`, `${BKT}/tegelwerk-herstellen-vervangen`, `${B}/kitwerk-vervangen`],
    articles: ["kitwerk-vervangen-wanneer-en-waarom", "schimmel-in-de-badkamer-blijvend-oplossen"],
  },
  {
    path: `${BKT}/schimmelreiniging-en-ventilatie`,
    name: "Schimmel & ventilatie",
    short: "Schimmel verwijderen en de oorzaak aanpakken: vocht en ventilatie.",
    h1: "Schimmel in de badkamer en ventilatie",
    title: "Schimmel badkamer verwijderen",
    description:
      "Schimmel in de badkamer die steeds terugkomt? We verwijderen schimmel en pakken de oorzaak aan met betere ventilatie. Zeeland en Amsterdam. Vraag offerte.",
    icon: "wind",
    intro: [
      "Schimmel in de badkamer is een van de meest gestelde vragen die we krijgen. De zwarte plekken op het plafond, in de hoeken en in de kit komen steeds terug, hoe vaak je ook schoonmaakt. Dat komt omdat schoonmaken het symptoom bestrijdt. De oorzaak is bijna altijd te veel vocht in de lucht dat niet weg kan.",
      "Bij elke douchebeurt komt veel waterdamp vrij. Als die niet snel wordt afgevoerd, slaat hij neer op de koudste plekken: het plafond, de buitenmuur, de hoeken. Daar groeit schimmel. Oude badkamers hebben vaak alleen een klein raampje of een zwakke afzuiger.",
      "We verwijderen de schimmel grondig, vervangen aangetaste kit en behandelen het plafond met een schimmelwerende saus. Daarnaast verbeteren we de ventilatie, met een krachtige afzuiger met vochtsensor of nalooptimer en een goede luchttoevoer via de deur.",
    ],
    signals: [
      "Zwarte plekken op plafond of in hoeken",
      "Schimmel die binnen weken terugkomt",
      "Beslagen spiegels die lang niet opdrogen",
      "Een muffe geur",
    ],
    steps: [
      { t: "Oorzaak", d: "We meten vocht in wand en lucht en controleren de afzuiging." },
      { t: "Verwijderen", d: "Schimmel grondig verwijderen en aangetaste kit vervangen." },
      { t: "Behandelen", d: "Plafond en wanden met een schimmelwerend systeem afwerken." },
      { t: "Ventilatie", d: "Afzuiger plaatsen of vervangen en luchttoevoer verbeteren." },
    ],
    duration: "Meestal één tot twee dagen, inclusief het plaatsen van een nieuwe afzuiger.",
    costFactors: ["Omvang van de schimmel", "Type afzuiging", "Kanaal of doorvoer nodig"],
    faqs: [
      { q: "Is schimmel schadelijk?", a: "Schimmel kan klachten geven aan luchtwegen, vooral bij gevoelige mensen. Neem het daarom serieus." },
      { q: "Helpt een raam open?", a: "Het helpt iets, maar vaak niet genoeg. Een afzuiger met nalooptijd werkt veel beter." },
      { q: "Kan de schimmel ook uit de muur komen?", a: "Ja, als er een lekkage achter de tegels is of vocht door de buitenmuur komt. Dat onderzoeken we ook." },
    ],
    related: ["/expertises/schade-herstel/vochtbestrijding", `${BKT}/voeg-en-kitwerk-vervangen`, "/expertises/renovatie-verbouw/verduurzaming/badkamer-renovatie"],
    articles: ["schimmel-in-de-badkamer-blijvend-oplossen", "vochtige-muren-oorzaken-en-oplossingen"],
  },
  {
    path: `${BKT}/tegelwerk-herstellen-vervangen`,
    name: "Tegelwerk",
    short: "Holle, gebarsten of losse tegels herstellen of vervangen.",
    h1: "Tegelwerk herstellen of vervangen",
    title: "Tegelwerk herstellen of vervangen",
    description:
      "Gebarsten, holle of losse tegels in badkamer, keuken of toilet? We herstellen of vervangen tegelwerk en controleren de ondergrond. Vraag een offerte aan.",
    icon: "layers",
    intro: [
      "Een gebarsten tegel of een tegel die hol klinkt, lijkt een cosmetisch probleem. Maar in een natte ruimte is het een risico. Water loopt via de scheur of de holle ruimte achter de tegel en tast de wand of vloer aan.",
      "Losse tegels zijn vaak een teken van iets anders. De lijm laat los door vocht, de ondergrond beweegt of er zit een lekkage achter. We kijken daarom niet alleen naar de tegel, maar ook naar wat erachter zit.",
      "Waar mogelijk vervangen we alleen de beschadigde tegels. Heb je nog reservetegels, dan is dat ideaal. Zo niet, dan zoeken we een passend alternatief of stellen we voor om een wand of vloer opnieuw te betegelen.",
    ],
    signals: ["Gebarsten of gebroken tegels", "Tegels die hol klinken", "Losliggende vloertegels", "Vocht achter het tegelwerk"],
    steps: [
      { t: "Beoordelen", d: "Tegels aftikken en de oorzaak van het loslaten zoeken." },
      { t: "Verwijderen", d: "Beschadigde tegels voorzichtig eruit halen." },
      { t: "Ondergrond", d: "Ondergrond herstellen en, waar nodig, opnieuw waterdicht maken." },
      { t: "Zetten en voegen", d: "Nieuwe tegels zetten, voegen en kitten." },
    ],
    sections: [{ h2: "Reservetegels bewaren", body: ["Laat bij een nieuwe badkamer of keuken altijd een paar reservetegels achter, inclusief de doos met het serienummer. Tegels worden na een paar jaar vaak niet meer gemaakt, en kleuren verschillen per productiepartij. Met reservetegels kan een beschadigde tegel onzichtbaar worden vervangen."] }],
    duration: "Plaatselijk herstel is vaak binnen een dag klaar, plus droogtijd van lijm en voeg.",
    costFactors: ["Aantal tegels", "Beschikbaarheid van passende tegels", "Herstel van de ondergrond"],
    faqs: [
      { q: "Kunnen jullie één tegel vervangen?", a: "Ja, als er een passende tegel is. Bewaar daarom altijd een paar reservetegels." },
      { q: "Waarom laten tegels los?", a: "Door vocht, beweging van de ondergrond of verkeerde lijm. We zoeken de oorzaak voordat we herstellen." },
      { q: "Kan over oude tegels heen getegeld worden?", a: "Soms wel, maar alleen als de oude tegels stevig vastzitten en de ruimte het toelaat." },
    ],
    related: [`${BKT}/voeg-en-kitwerk-vervangen`, `${BKT}/sanitair-en-meubels-vervangen`, "/expertises/schade-herstel/lekkages-vochtproblemen"],
    articles: ["schimmel-in-de-badkamer-blijvend-oplossen"],
  },
  {
    path: `${BKT}/sanitair-en-meubels-vervangen`,
    name: "Sanitair & meubels",
    short: "Toilet, wastafel, kranen of badmeubel vervangen zonder volledige renovatie.",
    h1: "Sanitair en badkamermeubels vervangen",
    title: "Sanitair en badmeubel vervangen",
    description:
      "Nieuw toilet, wastafel, kraan of badmeubel nodig? We vervangen sanitair zonder dat je hele badkamer eruit hoeft. Zeeland en Amsterdam. Vraag offerte aan.",
    icon: "bath",
    intro: [
      "Niet elke badkamer hoeft volledig gerenoveerd te worden. Vaak zijn de tegels en de waterdichting nog prima, maar is het sanitair versleten of gedateerd. Een nieuwe wastafel met meubel, een moderne mengkraan of een hangtoilet maakt dan al een groot verschil.",
      "We vervangen toiletten, wastafels, badmeubels, kranen, douchesets en spiegels. Daarbij controleren we de aansluitingen en afvoeren, en kitten we alles opnieuw af. Zo voorkom je lekkages bij de nieuwe aansluitingen.",
      "Voor corporaties en beheerders vervangen we sanitair bij mutaties met een vaste werkwijze. Zo is de woning snel klaar voor de nieuwe huurder.",
    ],
    signals: ["Lekkende kranen of stortbak", "Een gebarsten wastafel of toiletpot", "Een badmeubel dat opzwelt door vocht", "Een badkamer die er gedateerd uitziet"],
    steps: [
      { t: "Kiezen", d: "We helpen met maten en aansluitingen bij je keuze." },
      { t: "Demonteren", d: "Oud sanitair verwijderen en aansluitingen controleren." },
      { t: "Monteren", d: "Nieuw sanitair plaatsen en aansluiten." },
      { t: "Afwerken", d: "Kitten, testen op lekkages en opruimen." },
    ],
    sections: [{ h2: "Waar je op let bij nieuw sanitair", body: ["Let bij een nieuw toilet op de afstand van de afvoer tot de wand en het type aansluiting. Bij een wastafelmeubel tellen de breedte, de diepte en de plek van de sifon en de kranen. Een nieuwe mengkraan moet passen bij de waterdruk en het aantal kraangaten. Stuur ons een foto en de maten, dan controleren we vooraf of alles past. Zo voorkom je dat je met een mooi meubel zit dat net niet past. Ook adviseren we over waterbesparende kranen en spoelsystemen."] }],
    duration: "Meestal binnen één dag.",
    costFactors: ["Type en aantal onderdelen", "Aanpassingen aan aansluitingen", "Of sanitair door ons geleverd wordt"],
    faqs: [
      { q: "Mag ik zelf sanitair kopen?", a: "Ja. We controleren vooraf of het past bij je aansluitingen." },
      { q: "Kan een staand toilet een hangtoilet worden?", a: "Ja, met een inbouwreservoir. Dat vraagt wat meer werk aan de wand." },
      { q: "Voeren jullie oud sanitair af?", a: "Ja, we nemen het mee en voeren het af." },
    ],
    related: ["/expertises/renovatie-verbouw/verduurzaming/toiletrenovatie", `${BKT}/tegelwerk-herstellen-vervangen`, "/zakelijk"],
    articles: ["wat-kost-een-badkamerrenovatie"],
  },

  // ---------------------------------------------------------------- Interieur
  {
    path: I,
    name: "Interieuronderhoud",
    short: "Schilderwerk, vloeren, deuren, trapleuningen en hang- en sluitwerk.",
    h1: "Interieuronderhoud in Zeeland en Amsterdam",
    title: "Interieuronderhoud Zeeland en Amsterdam",
    description:
      "Interieuronderhoud: schilderwerk, vloeren, deuren, trapleuningen en hang- en sluitwerk. Voor particulier, VvE en corporatie. Vraag een offerte aan.",
    icon: "door",
    intro: [
      "Binnen slijt een huis door gewoon gebruik. Wanden krijgen deuken, deuren gaan klemmen, vloeren slijten en sloten gaan stroef. Losse klussen die blijven liggen, maken een huis rommelig en minder veilig.",
      "We doen het binnenonderhoud in één keer: schilderwerk aan wanden en plafonds, vloeren vervangen, deuren en trapleuningen vernieuwen en hang- en sluitwerk vervangen. Omdat we zelf stukadoors zijn, herstellen we eerst beschadigingen in de wand, zodat het schilderwerk strak wordt.",
      "Voor verhuurders en corporaties doen we dit werk ook bij mutaties. Eén partij die de woning in korte tijd weer verhuurklaar maakt.",
    ],
    signals: ["Beschadigde of vergeelde wanden", "Versleten vloeren", "Klemmende deuren of losse trapleuning", "Sloten die niet meer goed werken"],
    sections: [{ h2: "Combineer klussen in één ronde", body: ["Veel kleine binnenklussen blijven liggen omdat ze apart te klein lijken om iemand voor te laten komen. Door ze te combineren in één ronde, scheelt het voorrijkosten en ben je in één keer klaar. Maak een lijstje van alles wat je wilt laten doen, met foto's. Wij maken er een planning van, zodat de klussen in de juiste volgorde gebeuren: eerst herstellen, dan schilderen, dan vloeren."] }],
    duration: "Per ruimte vaak één tot drie dagen. Een complete woning bij mutatie plannen we in één aaneengesloten periode.",
    costFactors: ["Aantal ruimtes", "Soort werkzaamheden", "Materiaalkeuze"],
    faqs: [
      { q: "Doen jullie ook losse klussen?", a: "Ja. Ook één deur of één kamer schilderen." },
      { q: "Werken jullie stofarm?", a: "Ja, met afdekken, stofzuigers met afzuiging en dagelijks opruimen." },
      { q: "Doen jullie mutatiewerk?", a: "Ja, voor corporaties en verhuurders. Zie de pagina Zakelijk." },
    ],
    related: ["/stucwerk", "/expertises/renovatie-verbouw/verduurzaming/interieurverbouw", "/zakelijk"],
    articles: ["sausklaar-vs-behangklaar-stucwerk"],
  },
  {
    path: `${I}/schilderwerk-wanden-en-plafonds`,
    name: "Schilderwerk wanden & plafonds",
    short: "Strak sauswerk op een goed voorbereide ondergrond.",
    h1: "Schilderwerk voor wanden en plafonds",
    title: "Wanden en plafonds laten schilderen",
    description:
      "Wanden en plafonds strak laten sausen? Wij herstellen eerst de ondergrond en schilderen daarna egaal en streeploos. Zeeland en Amsterdam. Vraag offerte.",
    icon: "paint",
    intro: [
      "Een wand of plafond sausen lijkt eenvoudig. Toch zie je het verschil tussen een snelle verfbeurt en vakwerk meteen, vooral bij strijklicht. Gaatjes, scheurtjes en oude reparaties schijnen door de verf heen. Een strak resultaat begint daarom bij de ondergrond.",
      "Als stukadoors zijn we sterk in die voorbereiding. We vullen gaten, herstellen scheuren en zetten zo nodig een vlak opnieuw af. Daarna gronden we en sausen we in twee lagen met een goede muurverf. Zo krijg je een egale, streeploze wand.",
      "Op plafonds met vlekken van een oude lekkage of nicotine gebruiken we eerst een isolerende grondverf. Anders komen de vlekken door de nieuwe laag heen.",
    ],
    signals: ["Vergeelde of vlekkerige wanden", "Gaatjes en scheurtjes na verhuizing", "Vlekken van een oude lekkage", "Je wilt een andere kleur"],
    steps: [
      { t: "Afdekken", d: "Vloeren, meubels en kozijnen beschermen." },
      { t: "Herstellen", d: "Gaten vullen, scheuren repareren, schuren." },
      { t: "Gronden", d: "Een voorstrijk of isolerende grondlaag waar nodig." },
      { t: "Sausen", d: "Twee lagen muurverf, egaal en streeploos." },
    ],
    sections: [{ h2: "Mat, zijdemat of afwasbaar?", body: ["In woonkamers en slaapkamers kiezen de meeste mensen een matte muurverf. Die geeft een rustig beeld en verbergt kleine oneffenheden. In gangen, trappenhuizen en kinderkamers is een schrobvaste of afwasbare verf praktischer. Op plafonds gebruiken we een extra matte plafondverf, zodat aanzetten en strijklicht minder opvallen."] }],
    duration: "Een gemiddelde woonkamer is in één tot twee dagen klaar.",
    costFactors: ["Oppervlak", "Staat van de ondergrond", "Type verf"],
    faqs: [
      { q: "Welke verf gebruiken jullie?", a: "Een goed dekkende, schrobvaste muurverf. In natte ruimtes een vochtbestendige variant." },
      { q: "Kan ik in de kamer blijven?", a: "Moderne muurverf ruikt weinig. Wel is het handig de ruimte een dag niet te gebruiken." },
      { q: "Doen jullie ook houtwerk?", a: "Deuren en kozijnen binnen kunnen we meenemen. Vraag het in je offerte." },
    ],
    related: ["/stucwerk", `${I}/deuren-vervangen`, "/expertises/schade-herstel/interieur-en-afbouwschade"],
    articles: ["sausklaar-vs-behangklaar-stucwerk", "hoe-lang-moet-stucwerk-drogen"],
  },
  {
    path: `${I}/vloeren-vervangen`,
    name: "Vloeren vervangen",
    short: "Oude vloer eruit, ondervloer egaal, nieuwe vloer erin.",
    h1: "Vloeren vervangen in Zeeland en Amsterdam",
    title: "Vloer vervangen Zeeland en Amsterdam",
    description:
      "Vloer vervangen? We verwijderen de oude vloer, egaliseren de ondervloer en leggen PVC, laminaat of tegels. In Zeeland en Amsterdam. Vraag offerte aan.",
    icon: "layers",
    intro: [
      "Een nieuwe vloer verandert de hele ruimte. Maar een vloer is maar zo goed als wat eronder zit. Een oneffen ondervloer zie je terug in naden die openstaan, PVC dat de oneffenheden laat zien of tegels die hol liggen.",
      "We verwijderen de oude vloer, controleren de ondergrond en egaliseren waar nodig. Daarna leggen we de nieuwe vloer: PVC, laminaat, tegels of een andere afwerking. Plinten en overgangsprofielen werken we strak af.",
      "In appartementen gelden vaak geluidseisen van de VvE. Die controleren we vooraf, zodat de nieuwe vloer met de juiste ondervloer wordt gelegd.",
    ],
    signals: ["Versleten of beschadigde vloer", "Losliggende tegels of planken", "Een vloer die kraakt of verend aanvoelt", "Mutatie of verbouwing"],
    steps: [
      { t: "Opname", d: "Ondergrond, hoogtes en VvE-eisen controleren." },
      { t: "Verwijderen", d: "Oude vloer en lijmresten weg." },
      { t: "Egaliseren", d: "Ondervloer vlak en droog maken." },
      { t: "Leggen", d: "Nieuwe vloer leggen en plinten en profielen afwerken." },
    ],
    sections: [{ h2: "PVC, laminaat of tegels?", body: ["PVC is stil, warm en waterbestendig, maar laat oneffenheden in de ondervloer zien. Laminaat is voordelig en stevig, maar minder geschikt voor natte ruimtes. Tegels zijn onverwoestbaar en ideaal met vloerverwarming, maar kouder en harder. We helpen je kiezen op basis van de ruimte, het gebruik en de ondergrond. Ook letten we op de hoogte van de nieuwe vloer, zodat deuren nog vrij draaien en drempels zo laag mogelijk blijven."] }],
    duration: "Een gemiddelde woonkamer met egaliseren duurt twee tot vier dagen, inclusief droogtijd.",
    costFactors: ["Oppervlak", "Type vloer", "Egaliseren", "Geluidseisen"],
    faqs: [
      { q: "Moet de ondervloer altijd geëgaliseerd?", a: "Niet altijd. Bij PVC bijna altijd, bij laminaat soms. We meten het eerst." },
      { q: "Kan vloerverwarming eronder?", a: "Bij veel vloertypes wel. We adviseren een vloer die geschikt is voor vloerverwarming." },
      { q: "Mag ik in een appartement elke vloer leggen?", a: "Nee, vaak gelden geluidseisen. Check het huishoudelijk reglement van je VvE." },
    ],
    related: [`${I}/schilderwerk-wanden-en-plafonds`, "/expertises/renovatie-verbouw/verduurzaming/interieurverbouw", "/zakelijk"],
    articles: ["hoe-lang-moet-stucwerk-drogen"],
  },
  {
    path: `${I}/deuren-vervangen`,
    name: "Binnendeuren vervangen",
    short: "Nieuwe binnendeuren, strak afgehangen en goed sluitend.",
    h1: "Binnendeuren vervangen en afhangen",
    title: "Binnendeuren vervangen en afhangen",
    description:
      "Nieuwe binnendeuren laten plaatsen? We hangen deuren strak af, passen kozijnen aan en monteren hang- en sluitwerk. Zeeland en Amsterdam. Vraag offerte.",
    icon: "door",
    intro: [
      "Binnendeuren bepalen voor een groot deel de uitstraling van je interieur. Oude deuren met beschadigingen, verkeerde draairichting of een gedateerd model maken een huis minder fris. Nieuwe deuren geven veel effect voor een overzichtelijke investering.",
      "We meten de kozijnen op, adviseren over het type deur en hangen de nieuwe deuren strak af. Dat betekent: gelijke kieren, soepel sluitend en met hang- en sluitwerk dat goed werkt. Scheve kozijnen in oudere woningen passen we aan, of we vervangen ze.",
      "Ook voor brandwerende deuren in appartementencomplexen kun je bij ons terecht. Daar gelden specifieke eisen aan deur, kozijn en sluitwerk.",
    ],
    signals: ["Beschadigde of verouderde deuren", "Deuren die klemmen of niet sluiten", "Je wilt een andere stijl", "Scheve kozijnen"],
    steps: [
      { t: "Opmeten", d: "Kozijnen opmeten en de deur kiezen." },
      { t: "Voorbereiden", d: "Kozijnen controleren en waar nodig aanpassen." },
      { t: "Afhangen", d: "Deuren op maat maken en afhangen." },
      { t: "Afwerken", d: "Hang- en sluitwerk monteren en afstellen." },
    ],
    sections: [{ h2: "Deuren in oudere woningen", body: ["In jaren-30-woningen en oudere panden hebben deuren vaak afwijkende maten en zijn kozijnen niet meer haaks. Een standaarddeur past dan niet zonder aanpassing. We maken de deur op maat, of laten een deur op maat maken. Paneeldeuren die bij het karakter van het huis horen, kunnen we vaak ook herstellen in plaats van vervangen. Denk aan nieuwe scharnieren, het bijwerken van de onderkant en een nieuwe lak."] }],
    duration: "Meestal kunnen we meerdere deuren per dag plaatsen.",
    costFactors: ["Aantal en type deuren", "Aanpassingen aan kozijnen", "Hang- en sluitwerk"],
    faqs: [
      { q: "Moeten de kozijnen ook vervangen?", a: "Niet altijd. Als ze recht en stevig zijn, kunnen ze blijven. Een verfbeurt doet dan wonderen." },
      { q: "Kunnen jullie opdekdeuren plaatsen?", a: "Ja, stompe en opdekdeuren, passend bij je kozijnen." },
      { q: "Leveren jullie ook de deuren?", a: "Dat kan. Je kunt ze ook zelf kopen; we controleren dan de maten." },
    ],
    related: [`${I}/hang-en-sluitwerk-vervangen`, `${K}/deuren-en-kozijnen-vervangen`, `${I}/schilderwerk-wanden-en-plafonds`],
    articles: [],
  },
  {
    path: `${I}/trapleuningen-vervangen`,
    name: "Trapleuningen vervangen",
    short: "Een stevige, veilige leuning die bij je interieur past.",
    h1: "Trapleuningen vervangen of plaatsen",
    title: "Trapleuning vervangen of plaatsen",
    description:
      "Wiebelende of ontbrekende trapleuning? We plaatsen stevige, veilige trapleuningen van hout of metaal, op de juiste hoogte. Werkgebied Zeeland en Amsterdam.",
    icon: "building",
    intro: [
      "Een trapleuning gebruik je elke dag, vaak zonder erbij na te denken. Totdat hij wiebelt of losschiet. Voor kinderen en ouderen is een stevige leuning een kwestie van veiligheid.",
      "We vervangen losse of versleten trapleuningen en plaatsen nieuwe, van hout of metaal. Belangrijk is de bevestiging. Leuninghouders moeten in een stevige ondergrond zitten, niet alleen in pleister of gipsplaat. Daarom kijken we eerst wat er achter de wand zit.",
      "Ook een tweede leuning aan de andere kant van de trap is een goede investering als je langer in je huis wilt blijven wonen.",
    ],
    signals: ["Een wiebelende of losse leuning", "Ontbrekende leuning", "Je wilt langer zelfstandig thuis wonen", "Een gedateerde uitstraling"],
    steps: [
      { t: "Opmeten", d: "Traplengte, hoogte en ondergrond bekijken." },
      { t: "Kiezen", d: "Materiaal en model bepalen." },
      { t: "Bevestigen", d: "Leuninghouders stevig verankeren." },
      { t: "Afwerken", d: "Leuning monteren en de wand bijwerken." },
    ],
    sections: [{ h2: "Een tweede leuning voor ouderen", body: ["Veel valongelukken in huis gebeuren op de trap. Een leuning aan beide kanten geeft houvast met beide handen en maakt traplopen voor ouderen een stuk veiliger. Het is een kleine ingreep, die meestal binnen een paar uur klaar is. Combineer het met het vervangen van losse traptreden of het aanbrengen van antislipstrips, dan is de trap in één keer weer veilig."] }],
    duration: "Meestal binnen een halve dag.",
    costFactors: ["Lengte van de trap", "Materiaal", "Ondergrond"],
    faqs: [
      { q: "Op welke hoogte hoort een leuning?", a: "Meestal tussen ongeveer 80 en 100 centimeter, gemeten vanaf de voorkant van de traptrede. We stemmen het af op de gebruikers." },
      { q: "Kan een leuning in een gipswand?", a: "Alleen met de juiste pluggen of als er een regel achter zit. Anders adviseren we een andere bevestiging." },
      { q: "Plaatsen jullie ook een tweede leuning?", a: "Ja, dat is vaak een slimme aanpassing voor ouderen." },
    ],
    related: [`${I}/deuren-vervangen`, `${I}/hang-en-sluitwerk-vervangen`, I],
    articles: [],
  },
  {
    path: `${I}/hang-en-sluitwerk-vervangen`,
    name: "Hang- en sluitwerk",
    short: "Scharnieren, sloten en beslag die weer soepel en veilig werken.",
    h1: "Hang- en sluitwerk vervangen",
    title: "Hang- en sluitwerk vervangen",
    description:
      "Stroeve sloten of slappe scharnieren? We vervangen hang- en sluitwerk binnen en buiten, soepel en veilig. Zeeland, Brabant en Amsterdam. Vraag offerte.",
    icon: "key",
    intro: [
      "Hang- en sluitwerk zijn alle scharnieren, sloten, krukken en sluitplaten aan deuren en ramen. Na jaren gebruik worden ze stroef of slap. Een deur sluit niet meer goed, een slot draait zwaar of een raam gaat niet meer dicht.",
      "We vervangen en stellen hang- en sluitwerk af aan binnen- en buitendeuren en ramen. Bij buitendeuren en ramen op de begane grond adviseren we inbraakwerend hang- en sluitwerk.",
      "Voor verhuurders vervangen we bij mutaties sloten en cilinders, zodat de nieuwe huurder veilig de woning in kan.",
    ],
    signals: ["Stroeve of klemmende sloten", "Slappe scharnieren", "Ramen die niet goed sluiten", "Nieuwe bewoners of verloren sleutels"],
    steps: [
      { t: "Controle", d: "Deuren en ramen nalopen." },
      { t: "Advies", d: "Afstellen of vervangen, en eventueel inbraakwerend." },
      { t: "Vervangen", d: "Nieuw hang- en sluitwerk monteren." },
      { t: "Afstellen", d: "Alles soepel en goed sluitend afstellen." },
    ],
    sections: [{ h2: "Inbraakpreventie in de praktijk", body: ["De meeste inbraken gebeuren via deuren en ramen op de begane grond die eenvoudig open te wrikken zijn. Goede cilinders met kerntrekbeveiliging, veiligheidsbeslag en extra sluitpunten maken dat veel moeilijker. Ook ramen op de eerste verdieping die vanaf een plat dak of schuur bereikbaar zijn, verdienen aandacht. We lopen de woning met je na en adviseren waar extra beveiliging het meest oplevert. Daarnaast stellen we bestaande deuren en ramen af, zodat ze weer goed sluiten. Een deur die niet goed in het slot valt, is net zo kwetsbaar als een deur zonder goed slot."] }],
    duration: "Vaak binnen enkele uren.",
    costFactors: ["Aantal deuren en ramen", "Type sloten en beslag", "Inbraakwerendheid"],
    faqs: [
      { q: "Wat is inbraakwerend hang- en sluitwerk?", a: "Hang- en sluitwerk dat getest is op inbraakwerendheid. Vraag ons welk niveau bij jouw situatie past." },
      { q: "Kunnen jullie cilinders gelijksluitend maken?", a: "Ja, zodat je met één sleutel alle buitendeuren opent." },
      { q: "Doen jullie dit bij mutaties?", a: "Ja, voor corporaties en verhuurders." },
    ],
    related: [`${I}/deuren-vervangen`, `${K}/deuren-en-kozijnen-vervangen`, "/zakelijk"],
    articles: [],
  },

  // ---------------------------------------------------------------- Kozijnen
  {
    path: K,
    name: "Kozijnen",
    short: "Houtrotherstel, deuren en kozijnen vervangen en glas vervangen.",
    h1: "Kozijnen herstellen en vervangen in Zeeland",
    title: "Kozijnen herstellen en vervangen Zeeland",
    description:
      "Houtrot, tocht of enkel glas? We herstellen houtrot, vervangen deuren, kozijnen en glas in Zeeland, Brabant en Amsterdam. Vraag een offerte aan.",
    icon: "window",
    intro: [
      "Houten kozijnen gaan lang mee als je ze goed onderhoudt. Maar in een vochtig kustklimaat krijgt hout het zwaar. Op plekken waar water blijft staan, zoals de onderdorpel en de hoekverbindingen, ontstaat houtrot. Je ziet het aan bladderende verf en zacht hout.",
      "We herstellen houtrot, vervangen deuren en kozijnen en vervangen glas. Bij herstel frezen we het rotte hout weg en vullen we aan met een tweecomponenten houtreparatiemiddel of een ingezet stuk nieuw hout. Bij vervanging kies je tussen hout en kunststof.",
      "Kozijnen hebben veel invloed op vocht en energieverbruik. Tochtende kozijnen en enkel glas kosten warmte en geven condens. Daarom nemen we kitwerk, tochtwering en glas mee in ons advies.",
    ],
    signals: ["Zacht of rot hout in onderdorpels of hoeken", "Bladderende verf", "Tocht langs ramen en deuren", "Condens tussen dubbel glas"],
    duration: "Houtrotherstel en glas vervangen zijn meestal in één tot twee dagen klaar. Kozijnvervanging per gevel duurt enkele dagen.",
    costFactors: ["Omvang van de houtrot", "Hout of kunststof", "Type glas"],
    faqs: [
      { q: "Herstellen of vervangen?", a: "Als de houtrot beperkt is, is herstel vaak goedkoper en duurzamer. Is het kozijn op veel plekken aangetast, dan is vervangen beter." },
      { q: "Werken jullie aan monumenten?", a: "Ja, waar mogelijk herstellen we het originele hout. Bij monumenten is vervanging vaak vergunningplichtig." },
      { q: "Schilderen jullie het ook?", a: "Herstelde delen schilderen we bij. Voor complete schilderbeurten werken we met een vaste schilder." },
    ],
    related: [`${K}/houtrotherstel`, `${K}/glas-vervangen`, DG],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },
  {
    path: `${K}/houtrotherstel`,
    name: "Houtrotherstel",
    short: "Rot hout eruit, duurzaam aangevuld en weer dicht geschilderd.",
    h1: "Houtrotherstel aan kozijnen en deuren",
    title: "Houtrot herstellen aan kozijnen",
    description:
      "Houtrot in kozijnen of deuren? We frezen rot hout weg en herstellen duurzaam met tweecomponentenmiddel of nieuw hout. Zeeland en Brabant. Vraag offerte.",
    icon: "window",
    intro: [
      "Houtrot ontstaat als hout lang nat blijft. Water dringt via een scheurtje in de verf of een open naad het hout in en kan er niet meer uit. Schimmels breken het hout dan langzaam af. Vooral onderdorpels, hoekverbindingen en de onderkant van deuren zijn kwetsbaar.",
      "Bij houtrotherstel verwijderen we al het aangetaste hout, tot we op gezond hout zitten. Kleinere plekken vullen we op met een tweecomponenten houtreparatiesysteem. Grotere stukken vervangen we door nieuw hout, verlijmd en geschroefd. Daarna werken we het in de grondverf en lakken we het af.",
      "Belangrijk is dat de oorzaak verdwijnt. Een naad die openstaat, een dorpel zonder afschot of een kitvoeg die loslaat. Anders begint het rot op dezelfde plek opnieuw.",
    ],
    signals: ["Zacht hout als je erin drukt", "Bladderende verf op de onderdorpel", "Donkere verkleuring in het hout", "Open naden in hoekverbindingen"],
    steps: [
      { t: "Opsporen", d: "We prikken het hout na en bepalen de omvang." },
      { t: "Wegfrezen", d: "Rot hout volledig verwijderen." },
      { t: "Herstellen", d: "Aanvullen met reparatiesysteem of nieuw hout." },
      { t: "Afwerken", d: "Schuren, gronden en aflakken, naden dichten." },
    ],
    sections: [{ h2: "Houtrot voorkomen", body: ["Houtrot begint bijna altijd op dezelfde plekken: de onderdorpel, de hoekverbindingen en de onderkant van deuren. Controleer die plekken elk voorjaar. Een scheurtje in de verf of een open naad is een signaal om bij te werken voordat er water in komt. Houd ook de kit rond het glas en de aansluiting op de muur in goede staat."] }],
    duration: "Meestal één tot twee dagen, afhankelijk van het aantal plekken.",
    costFactors: ["Aantal en grootte van de plekken", "Reparatiemiddel of nieuw hout", "Schilderwerk"],
    faqs: [
      { q: "Hoe lang houdt houtrotherstel?", a: "Goed uitgevoerd en onderhouden gaat het vele jaren mee. Regelmatig schilderen is belangrijk." },
      { q: "Is houtrot gevaarlijk?", a: "Bij dragende delen, zoals een balk of lateiconstructie, kan het de sterkte aantasten. Bij kozijnen gaat het vooral om lekkage en tocht." },
      { q: "Wanneer is het beste moment?", a: "Bij droog weer, voorafgaand aan een schilderbeurt." },
    ],
    related: [K, `${K}/deuren-en-kozijnen-vervangen`, "/expertises/schade-herstel/lekkages-vochtproblemen"],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },
  {
    path: `${K}/deuren-en-kozijnen-vervangen`,
    name: "Deuren & kozijnen vervangen",
    short: "Nieuwe buitendeuren en kozijnen in hout of kunststof.",
    h1: "Buitendeuren en kozijnen vervangen",
    title: "Buitendeuren en kozijnen vervangen",
    description:
      "Kozijnen of buitendeuren vervangen in hout of kunststof? We plaatsen, isoleren, kitten en stucen netjes af. Zeeland, Brabant en Amsterdam. Vraag offerte.",
    icon: "door",
    intro: [
      "Als kozijnen of buitendeuren op veel plekken rot zijn, of slecht isoleren, is vervangen de beste keuze. Nieuwe kozijnen met goed glas en tochtwering maken je huis warmer, stiller en veiliger.",
      "We meten op, adviseren over materiaal en profiel en plaatsen de nieuwe kozijnen. Het verschil zit in de aansluiting. We isoleren de naad tussen kozijn en muur, dichten hem luchtdicht aan de binnenkant en waterdicht aan de buitenkant. Binnen stucen we de dagkanten strak bij, zodat je geen beschadigingen ziet.",
      "Bij monumenten en in beschermd stadsgezicht gelden vaak eisen aan materiaal en profiel. We helpen je met de juiste keuze.",
    ],
    signals: ["Veel houtrot op meerdere plekken", "Tocht en koude", "Enkel glas of slecht sluitende ramen", "Je wilt een andere indeling of draairichting"],
    steps: [
      { t: "Inmeten", d: "Exacte maten en aansluitingen opnemen." },
      { t: "Bestellen", d: "Kozijnen op maat laten maken." },
      { t: "Plaatsen", d: "Oud kozijn eruit, nieuw kozijn erin, stellen en verankeren." },
      { t: "Aansluiten", d: "Isoleren, kitten en dagkanten stucen." },
    ],
    sections: [{ h2: "Aansluiting op de muur: luchtdicht en waterdicht", body: ["De naad tussen kozijn en muur is een bekende bron van tocht, vocht en geluid. Aan de binnenkant dichten we die luchtdicht af, zodat er geen warme, vochtige lucht in de naad kan. Aan de buitenkant waterdicht maar dampopen, zodat vocht dat toch in de naad komt, weer naar buiten kan. Daartussen komt isolatie. Zo voorkom je condens, schimmel en houtrot rond de nieuwe kozijnen."] }],
    duration: "Per kozijn vaak een dag, inclusief afwerking binnen.",
    costFactors: ["Aantal en grootte", "Hout of kunststof", "Glas en hang- en sluitwerk", "Afwerking binnen"],
    faqs: [
      { q: "Hout of kunststof?", a: "Hout past bij oudere panden en is goed te herstellen. Kunststof vraagt minder onderhoud. Bij monumenten is hout vaak verplicht." },
      { q: "Moet het stucwerk binnen opnieuw?", a: "De dagkanten wel. Dat doen we zelf, zodat het strak aansluit." },
      { q: "Heb ik een vergunning nodig?", a: "Bij gelijkblijvend uiterlijk meestal niet. Bij monumenten of als het aanzicht verandert soms wel." },
    ],
    related: [`${K}/glas-vervangen`, `${K}/houtrotherstel`, `${I}/hang-en-sluitwerk-vervangen`],
    articles: ["kitwerk-vervangen-wanneer-en-waarom"],
  },
  {
    path: `${K}/glas-vervangen`,
    name: "Glas vervangen",
    short: "Gebroken of lekkend glas vervangen door isolerend glas.",
    h1: "Glas vervangen: HR++ en triple glas",
    title: "Glas vervangen door HR++ of triple",
    description:
      "Gebroken glas, condens tussen de ruiten of nog enkel glas? We vervangen glas door HR++ of triple glas in je bestaande kozijn. Vraag een offerte aan.",
    icon: "window",
    intro: [
      "Glas vervangen kan om verschillende redenen. Een ruit is gebroken, er zit condens tussen de twee glasbladen, of je hebt nog enkel of oud dubbel glas. Oud glas laat veel warmte door en geeft koude plekken bij het raam.",
      "We vervangen glas in je bestaande kozijn, als dat kozijn in goede staat is. Daarbij controleren we of de sponning diep genoeg is voor dikker isolatieglas. Zo niet, dan kan er soms een aangepaste glaslat op, of adviseren we een ander soort glas.",
      "Na het plaatsen zetten we het glas waterdicht af met kit of glasrubbers. Zo blijft het kozijn droog en voorkom je houtrot.",
    ],
    signals: ["Gebroken of gebarsten ruit", "Condens tussen de glasbladen", "Enkel of oud dubbel glas", "Koude tocht bij het raam"],
    steps: [
      { t: "Opmeten", d: "Glasmaat en sponningdiepte bepalen." },
      { t: "Bestellen", d: "Glas op maat laten maken." },
      { t: "Plaatsen", d: "Oud glas eruit, nieuw glas erin." },
      { t: "Afdichten", d: "Glaslatten en kit of rubbers aanbrengen." },
    ],
    sections: [{ h2: "Condens tussen de ruiten", body: ["Zie je condens of een waas tussen de twee glasbladen van dubbel glas? Dan is de randafdichting van de ruit kapot en is er lucht met vocht tussen de glasbladen gekomen. Schoonmaken kan dan niet meer, en de isolatiewaarde is grotendeels verdwenen. De enige oplossing is de ruit vervangen."] }],
    duration: "Plaatsen kost meestal enkele uren per raam, na de levertijd van het glas.",
    costFactors: ["Afmetingen en aantal ruiten", "Type glas", "Aanpassing van glaslatten"],
    faqs: [
      { q: "Past HR++ glas in mijn kozijn?", a: "Vaak wel, maar het hangt af van de sponningdiepte. We meten het voor je op." },
      { q: "Wat is het verschil tussen HR++ en triple glas?", a: "Triple glas isoleert nog beter, maar is dikker en zwaarder. Niet elk kozijn is daar geschikt voor." },
      { q: "Wat als mijn ruit vannacht kapot is gegaan?", a: "Bel of app ons. We kunnen het raam tijdelijk dichtmaken tot het nieuwe glas er is." },
    ],
    related: [`${K}/deuren-en-kozijnen-vervangen`, K, "/expertises/schade-herstel/storm-en-natuurschade"],
    articles: [],
  },
];
